### ISSUE TITLE
No support for 'has' or 'whereHas' queries.

### ISSUE THREAD

**Issue by jr-cobweb** [johnrich85/eloquent-query-modifier#2]
At the moment, there is no way to add 'has' or 'whereHas' queries to the builder using EQM. Suggest this be added.

Input to EQM could look as follows:

~~~~
        $params = [
            'has'  => [
                'Products', //Basic 'has' without parameters
                'Members' => [ //Supports all of the existing modifiers.
                    'sort' => 'name'
                ]
            ]
        ];
	
~~~~

**In this instance:**

- Products would be loaded using a simple 'has' query.
- Members would be loaded using a 'whereHas' query. This would require a callback function to be generated. Callbacks passed via the 'whereHas' method run on a new query builder instance (I believe), so this would possibly mean creating a new instance of the EQM and applying it to the builder. Passing in all of the parameters beneath the 'Members' index.

**Notes:**

- Should probably look into implementing 'with' queries the same way.
- In which case, need to handle scenario whereby both 'with' and 'has' queries are being applied (filters should only be applied to one or the other).
- When adding a 'has' query, should probably look into automatically adding an eager load.
- Need to ensure has/whereHas queries support the count/count operator parameters.

**Comment by johnrich85** [comment]
This has now been implemented.
